version: '3.1'

services:
  postgres:
    image: postgres:14.5-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080

  bytebase:
    image: bytebase/bytebase:2.15.0
    restart: always
    ports:
      - 9091:8080
    volumes:
      - .bytebase/data:/var/opt/bytebase